import type { Metadata } from "next";
import { Roboto, Caveat } from "next/font/google";
import ToggleBodyClass from "../../components/elements/Togglebtn";
import SwitcherMenu from "../../components/elements/ColorStyle";

import "../../public/assets/css/bootstrap.css";
import "../../public/assets/css/rtl.css";
import "../../public/assets/css/style.css";
import "../../public/assets/css/responsive.css";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/autoplay";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "700"],
  variable: "--roboto",
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-caveat",
});

export const metadata: Metadata = {
  title: "Medicinsk React Next Js Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600;700&family=Caveat:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${roboto.variable} ${caveat.variable} { fontFamily: "'Source Sans Pro', sans-serif" }`}>
        {children}
        <ToggleBodyClass/>
        <SwitcherMenu />
      </body>
    </html>
  );
}
